## catalog of libraries and plugins used to build the DacWizard project

[versions]

checkstyle = "9.3"
jme = "3.8.0-beta1"

[libraries]

## select one version of LWJGL:
#lwjgl = { module = "org.jmonkeyengine:jme3-lwjgl", version.ref = "jme" } # for LWJGL 2.x
lwjgl = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" } # for LWJGL 3.x

heart = "com.github.stephengold:Heart:9.2.0"
jme3-awt-dialogs = { module = "org.jmonkeyengine:jme3-awt-dialogs", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }
jme3-utilities-nifty = "com.github.stephengold:jme3-utilities-nifty:0.9.37"
minie = "com.github.stephengold:Minie:9.0.1"
nifty-style-black = "com.github.nifty-gui:nifty-style-black:1.4.3"
wes = "com.github.stephengold:Wes:0.8.1"

[bundles]

[plugins]
