## catalog of libraries and plugins used to build and run the DacWizard project

[versions]

checkstyle = "14.1.0"
jme = "3.10.0-beta2"

[libraries]

## select one version of LWJGL:
#lwjgl = { module = "org.jmonkeyengine:jme3-lwjgl", version.ref = "jme" } # for LWJGL 2.x
lwjgl = { module = "org.jmonkeyengine:jme3-lwjgl3", version.ref = "jme" } # for LWJGL 3.x

heart = "com.github.stephengold:Heart:9.4.0-test1"

jme3-awt-dialogs = { module = "org.jmonkeyengine:jme3-awt-dialogs", version.ref = "jme" }
jme3-desktop = { module = "org.jmonkeyengine:jme3-desktop", version.ref = "jme" }
jme3-jogg = { module = "org.jmonkeyengine:jme3-jogg", version.ref = "jme" }
jme3-plugins = { module = "org.jmonkeyengine:jme3-plugins", version.ref = "jme" }

jme3-utilities-nifty = "com.github.stephengold:jme3-utilities-nifty:0.9.37"
minie = "com.github.stephengold:Minie:10.0.0-test1"
nifty-style-black = "com.github.nifty-gui:nifty-style-black:1.4.3"
wes = "com.github.stephengold:Wes:0.8.4"

[bundles]

[plugins]
